function toggleVideo(button, videoDiv, videoUrl) {
    button.addEventListener("click", function() {
      videoDiv.classList.toggle("span_video");
      videoDiv.innerHTML = `<iframe class="video" src="${videoUrl}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>`;
      videoDiv.parentElement.classList.toggle("div_botonvideo_grande");
    });
  }

  toggleVideo(
    document.getElementById("prscontinnnn"),
    document.getElementById("prscontinnnna"),
    "https://www.youtube.com/embed/l2Bbg3ATN9g"
  );
  toggleVideo(
    document.getElementById("prcontindosss"),
    document.getElementById("prcontindosssa"),
    "https://www.youtube.com/embed/L31N6QLRVBg"
  );
  toggleVideo(
    document.getElementById("simplprsss"),
    document.getElementById("simplprsssa"),
    "https://www.youtube.com/embed/gKoHcwKsXAs"
  );
  toggleVideo(
    document.getElementById("thprsperf"),
    document.getElementById("thprsperfa"),
    "https://www.youtube.com/embed/GHqaM6-woYE"
  );
  toggleVideo(
    document.getElementById("futtwithwill"),
    document.getElementById("futtwithwilla"),
    "https://www.youtube.com/embed/fSXcZvLD2tE"
  );
  toggleVideo(
    document.getElementById("futwigoin"),
    document.getElementById("futwigoina"),
    "https://www.youtube.com/embed/mwLkttX69MU"
  );
  toggleVideo(
    document.getElementById("prpefcintu"),
    document.getElementById("prpefcintua"),
    "https://www.youtube.com/embed/2PZcD5szVPE"
  );
  toggleVideo(
    document.getElementById("pstsimplll"),
    document.getElementById("pstsimpllla"),
    "https://www.youtube.com/embed/B8jdh5oHoVI"
  );



  toggleVideo(
    document.getElementById("sjkdhfsfdsddf"),
    document.getElementById("sjkdhfsfdsddfa"),
    "https://www.youtube.com/embed/EZBgxdsgJPg"
  );
  toggleVideo(
    document.getElementById("nsdisudhfkjs"),
    document.getElementById("nsdisudhfkjsa"),
    "https://www.youtube.com/embed/PWfwVTOLHgY"
  );
  toggleVideo(
    document.getElementById("Thearticles"),
    document.getElementById("Thearticlesa"),
    "https://www.youtube.com/embed/CKG8X3oK3_0"
  );
  toggleVideo(
    document.getElementById("Adjectivesjsdjs"),
    document.getElementById("Adjectivesjsdjsa"),
    "https://www.youtube.com/embed/jRM47iw-zG0"
  );
  toggleVideo(
    document.getElementById("Prepositionssadasd"),
    document.getElementById("Prepositionssadasda"),
    "https://www.youtube.com/embed/e1ov46D2yfI"
  );
  toggleVideo(
    document.getElementById("Comparativesdsfsdf"),
    document.getElementById("Comparativesdsfsdfa"),
    "https://www.youtube.com/embed/KQYTPsA4bg4"
  );
  toggleVideo(
    document.getElementById("Connectorssadas"),
    document.getElementById("Connectorssadasa"),
    "https://www.youtube.com/embed/vHiQ-wZqMMo"
  );
  toggleVideo(
    document.getElementById("Superlativessaad"),
    document.getElementById("Superlativessaada"),
    "https://www.youtube.com/embed/E7-38Qp4TJM"
  );
  toggleVideo(
    document.getElementById("Modal__verbI"),
    document.getElementById("Modal__verbIa"),
    "https://www.youtube.com/embed/CuAxOElSdCY"
  );
  toggleVideo(
    document.getElementById("ModalsafverbsII"),
    document.getElementById("ModalsafverbsIIa"),
    "https://www.youtube.com/embed/2TAXoZqQC1M"
  );
  toggleVideo(
    document.getElementById("dsgdgasgdggad"),
    document.getElementById("dsgdgasgdggada"),
    "https://www.youtube.com/embed/kI7NBgzWuko"
  );
  toggleVideo(
    document.getElementById("bvfbfds"),
    document.getElementById("bvfbfdsa"),
    "https://www.youtube.com/embed/S921oaI-LA4"
  );


  toggleVideo(
    document.getElementById("sdfasdfasdf"),
    document.getElementById("sdfasdfasdfa"),
    "https://www.youtube.com/embed/51drdcM9Owc"
  );
  toggleVideo(
    document.getElementById("dfsdfsdfsdf"),
    document.getElementById("dfsdfsdfsdfa"),
    "https://www.youtube.com/embed/9vBM5p11HBE"
  );
  toggleVideo(
    document.getElementById("dsfjshdkjfhksd"),
    document.getElementById("dsfjshdkjfhksda"),
    "https://www.youtube.com/embed/CVI5EfX8H_I"
  );
  toggleVideo(
    document.getElementById("kjhjhkjhkj"),
    document.getElementById("kjhjhkjhkja"),
    "https://www.youtube.com/embed/IvA14Mj69Y4"
  );
  toggleVideo(
    document.getElementById("Prepositikasdjfjkonssadasd"),
    document.getElementById("Prepositikasdjfjkonssadasda"),
    "https://www.youtube.com/embed/T3TzSt4YSrI"
  );
  toggleVideo(
    document.getElementById("fsdgsfdgsdf"),
    document.getElementById("fsdgsfdgsdfa"),
    "https://www.youtube.com/embed/SJFrhbY0seQ"
  );