function toggleVideo(button, videoDiv, videoUrl) {
    button.addEventListener("click", function() {
      videoDiv.classList.toggle("span_video");
      videoDiv.innerHTML = `<iframe class="video" src="${videoUrl}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>`;
      videoDiv.parentElement.classList.toggle("div_botonvideo_grande");
    });
  }

  toggleVideo(
    document.getElementById("sajfjsjsjsjsjsa"),
    document.getElementById("sajfjsjsjsjsjsaa"),
    "https://www.youtube.com/embed/qrbYLGfiOkE"
  );

  toggleVideo(
    document.getElementById("sadasdasd"),
    document.getElementById("sadasdasda"),
    "https://www.youtube.com/embed/Z1LV5H789Tg?si=D0RVUCqjShstmarm"
  );
  toggleVideo(
    document.getElementById("sgsgsgs"),
    document.getElementById("sgsgsgsa"),
    "https://www.youtube.com/embed/HjU7PyWakYQ"
  );
  toggleVideo(
    document.getElementById("kjkjkj"),
    document.getElementById("kjkjkja"),
    "https://www.youtube.com/embed/BukA-PGuC30"
  );
  toggleVideo(
    document.getElementById("nffkfkf"),
    document.getElementById("nffkfkfa"),
    "https://www.youtube.com/embed/zD8RaWDqPg4"
  );
  toggleVideo(
    document.getElementById("viddsf"),
    document.getElementById("viddsfa"),
    "https://www.youtube.com/embed/E9Uhp0LkJ3o"
  );
  toggleVideo(
    document.getElementById("fisndiid"),
    document.getElementById("fisndiida"),
    "https://www.youtube.com/embed/30FSru1OOfI"
  );
  toggleVideo(
    document.getElementById("saasfaasfasf"),
    document.getElementById("saasfaasfasfa"),
    "https://www.youtube.com/embed/E9Uhp0LkJ3o"
  );
  toggleVideo(
    document.getElementById("sfasafnfk"),
    document.getElementById("sfasafnfka"),
    "https://www.youtube.com/embed/30FSru1OOfI"
  );
  toggleVideo(
    document.getElementById("ddddd"),
    document.getElementById("ddddda"),
    "https://www.youtube.com/embed/rh0hSga2gRM"
  );
  toggleVideo(
    document.getElementById("dvsvsdv"),
    document.getElementById("dvsvsdva"),
    "https://www.youtube.com/embed/GSSkAZGo5pE"
  );
  toggleVideo(
    document.getElementById("dsajksafsd"),
    document.getElementById("dsajksafsda"),
    "https://www.youtube.com/embed/A34wJfEC7dc"
  );
  toggleVideo(
    document.getElementById("safkasf"),
    document.getElementById("safkasfa"),
    "https://www.youtube.com/embed/k6K6tIWefyE"
  );
  toggleVideo(
    document.getElementById("fdndfkdlfv"),
    document.getElementById("fdndfkdlfva"),
    "https://www.youtube.com/embed/9mL0VHo289k"
  );
  toggleVideo(
    document.getElementById("sdfasdfasa"),
    document.getElementById("sdfasdfasaa"),
    "https://www.youtube.com/embed/CV8Ia0lTS2s"
  );
  toggleVideo(
    document.getElementById("ccccccccccccc"),
    document.getElementById("ccccccccccccca"),
    "https://www.youtube.com/embed/ictDSzzi3Kw"
  );
  toggleVideo(
    document.getElementById("sddfvffffffd"),
    document.getElementById("sddfvffffffda"),
    "https://www.youtube.com/embed/4piLLWMCPog"
  );
  toggleVideo(
    document.getElementById("fdvfvfvfvvv"),
    document.getElementById("fdvfvfvfvvva"),
    "https://www.youtube.com/embed/XcCnaf0eYvU"
  );
  toggleVideo(
    document.getElementById("fvfvfvddd"),
    document.getElementById("fvfvfvddda"),
    "https://www.youtube.com/embed/T8OpwgSfEMc"
  );
  toggleVideo(
    document.getElementById("dsfadfadva"),
    document.getElementById("dsfadfadvaa"),
    "https://www.youtube.com/embed/5tmaW6U8tT4"
  );
  toggleVideo(
    document.getElementById("dfasvavaaa"),
    document.getElementById("dfasvavaaaa"),
    "https://www.youtube.com/embed/bh3YQGI1Bd4"
  );
  toggleVideo(
    document.getElementById("fdnvfdnka"),
    document.getElementById("fdnvfdnkaa"),
    "https://www.youtube.com/embed/3jna5adcFPk"
  );
  toggleVideo(
    document.getElementById("sdfsdfa"),
    document.getElementById("sdfsdfaa"),
    "https://www.youtube.com/embed/Fkk0N3JGm2Y"
  );

  toggleVideo(
    document.getElementById("Literaturadelaedadmedia"),
    document.getElementById("Literaturadelaedadmediaa"),
    "https://www.youtube.com/embed/P4UYFkrHzfA"
  );
  toggleVideo(
    document.getElementById("Elasfrenacimiento"),
    document.getElementById("Elasfrenacimientoa"),
    "https://www.youtube.com/embed/qXM4IdPgTJQ"
  );
  toggleVideo(
    document.getElementById("Cómoseformónuestraculturaliteraria"),
    document.getElementById("Cómoseformónuestraculturaliterariaa"),
    "https://www.youtube.com/embed/cvZHf-G7g58"
  );
  toggleVideo(
    document.getElementById("Lafsailustración"),
    document.getElementById("Lafsailustracióna"),
    "https://www.youtube.com/embed/_Va5i-txPgg"
  );
  toggleVideo(
    document.getElementById("Elasdromanticismo"),
    document.getElementById("Elasdromanticismoa"),
    "https://www.youtube.com/embed/O-aH_l0FGsg"
  );
  toggleVideo(
    document.getElementById("extosliterarioslanovela"),
    document.getElementById("extosliterarioslanovelaa"),
    "https://www.youtube.com/embed/OnR0eEJN3Sw"
  );
  toggleVideo(
    document.getElementById("Textosliterarioslapoesía"),
    document.getElementById("Textosliterarioslapoesíaa"),
    "https://www.youtube.com/embed/Uj3PSmr2e2I"
  );
  toggleVideo(
    document.getElementById("Elveapscuento"),
    document.getElementById("Elveapscuentoa"),
    "https://www.youtube.com/embed/_BaRtSzs3g4"
  );
  toggleVideo(
    document.getElementById("Elasfdrealismo"),
    document.getElementById("Elasfdrealismoa"),
    "https://www.youtube.com/embed/EEKqiEuM4Vs"
  );
  toggleVideo(
    document.getElementById("extoargumentativoestructura"),
    document.getElementById("extoargumentativoestructuraa"),
    "https://www.youtube.com/embed/q5jso8iXRbQ"
  );
  toggleVideo(
    document.getElementById("Textosicónicoscomichistorietainforgrafía"),
    document.getElementById("Textosicónicoscomichistorietainforgrafíaa"),
    "https://www.youtube.com/embed/XpmSxj-8BKk"
  );
  toggleVideo(
    document.getElementById("Textosinformativosyexpositivos"),
    document.getElementById("Textosinformativosyexpositivosa"),
    "https://www.youtube.com/embed/kF3OM3l3PVQ"
  );
  toggleVideo(
    document.getElementById("Estrategiasdecomprensiónlectora"),
    document.getElementById("Estrategiasdecomprensiónlectoraa"),
    "https://www.youtube.com/embed/YIbxTuVE3xg"
  );
  toggleVideo(
    document.getElementById("ksfdgdfgdfgdfdl"),
    document.getElementById("ksfdgdfgdfgdfdla"),
    "https://www.youtube.com/embed/LxeGp6SZm1M"
  );
  toggleVideo(
    document.getElementById("Capitksldalismo"),
    document.getElementById("Capitksldalismoa"),
    "https://www.youtube.com/embed/fmq1VmBZCSM"
  );
  toggleVideo(
    document.getElementById("Estado_democracia_y_formas_de_gosdfsdbierno"),
    document.getElementById("Estado_democracia_y_formas_de_gosdfsdbiernoa"),
    "https://www.youtube.com/embed/HZRJ3hJJwUA"
  );
  toggleVideo(
    document.getElementById("Organización_del_estadsfsafasfo_Colombiano"),
    document.getElementById("Organización_del_estadsfsafasfo_Colombianoa"),
    "https://www.youtube.com/embed/ZV1RFcxXR5g"
  );
  toggleVideo(
    document.getElementById("Derecho_internacional_públsafasfasfico"),
    document.getElementById("Derecho_internacional_públsafasfasficoa"),
    "https://www.youtube.com/embed/VoWc7SpmP3k"
  );
  toggleVideo(
    document.getElementById("Derecho_internacional_hudasdasmanitario"),
    document.getElementById("Derecho_internacional_hudasdasmanitarioa"),
    "https://www.youtube.com/embed/-oMgMWcG6ZA"
  );
  toggleVideo(
    document.getElementById("Problsaduales_del_mundo"),
    document.getElementById("Problsaduales_del_mundoa"),
    "https://www.youtube.com/embed/diBNr87EB5c"
  );

  toggleVideo(
    document.getElementById("Sobre_sfadfia"),
    document.getElementById("Sobre_sfadfiaa"),
    "https://www.youtube.com/embed/dbMD0pk6v7M"
  );
  toggleVideo(
    document.getElementById("ksfdkldsf"),
    document.getElementById("ksfdkldsfa"),
    "https://www.youtube.com/embed/hzBmLL7wS-4"
  );
  toggleVideo(
    document.getElementById("dfaadfasdddsd"),
    document.getElementById("dfaadfasdddsda"),
    "https://www.youtube.com/embed/qDsEY8Ar9so"
  );
  toggleVideo(
    document.getElementById("Vanguardias"),
    document.getElementById("Vanguardiasa"),
    "https://www.youtube.com/embed/X9uAlXZsnc0"
  );

 