function toggleVideo(button, videoDiv, videoUrl) {
    button.addEventListener("click", function() {
      videoDiv.classList.toggle("span_video");
      videoDiv.innerHTML = `<iframe class="video" src="${videoUrl}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>`;
      videoDiv.parentElement.classList.toggle("div_botonvideo_grande");
    });
  }

  toggleVideo(
    document.getElementById("dsdsdsdsd"),
    document.getElementById("dsdsdsdsda"),
    "https://www.youtube.com/embed/-s50UO0GHiU?si=lpqvShM1JF93cwjm"
  );
  toggleVideo(
    document.getElementById("gtgtgtgg"),
    document.getElementById("gtgtgtgga"),
    "https://www.youtube.com/embed/AqPCvyWUmg8?si=2QsPtW1PtdiddpnF"
  );
  toggleVideo(
    document.getElementById("dasdsdftrfvd"),
    document.getElementById("dasdsdftrfvda"),
    "https://www.youtube.com/embed/lgKCXeF56O4?si=gXveVcCtr00Xbe6-"
  );
  toggleVideo(
    document.getElementById("asftrtge"),
    document.getElementById("asftrtgea"),
    "https://www.youtube.com/embed/RGVjGMSkR6o?si=i1Qii9Z7OMUwMsAv"
  );
  toggleVideo(
    document.getElementById("dafarefaesd"),
    document.getElementById("dafarefaesda"),
    "https://www.youtube.com/embed/xcOR55oiHdk?si=c-80rpoJn_CJ5mua"
  );
  toggleVideo(
    document.getElementById("sdaklfasdjllkasdf"),
    document.getElementById("sdaklfasdjllkasdfa"),
    "https://www.youtube.com/embed/Kkwyigq865k?si=AY6bZxEf07Vleej5"
  );
  toggleVideo(
    document.getElementById("sfasfsadfasdfsd"),
    document.getElementById("sfasfsadfasdfsda"),
    "https://www.youtube.com/embed/RLmNJ9FeIHI?si=k4b_rl2vFYLA8T0u"
  );
  toggleVideo(
    document.getElementById("gdfsgsfdfdsfds"),
    document.getElementById("gdfsgsfdfdsfdsa"),
    "https://www.youtube.com/embed/E_HFyAXkJ5g?si=AW2Cqt_c3hh3SkIK"
  );
  toggleVideo(
    document.getElementById("Reduccióndetérminos"),
    document.getElementById("Reduccióndetérminosa"),
    "https://www.youtube.com/embed/MKoeyBjD2KU?si=4GPGB3WEJDycSgfN"
  );
  toggleVideo(
    document.getElementById("Racionasslización"),
    document.getElementById("Racionasslizacióna"),
    "https://www.youtube.com/embed/7eqsu7oTYgw?si=Bn1s1c85vW72_kOt"
  );
  toggleVideo(
    document.getElementById("safefeeeeee"),
    document.getElementById("safefeeeeeea"),
    "https://www.youtube.com/embed/272uMSw54fU?si=uhEmk1JPmNQ-4CUT"
  );
  toggleVideo(
    document.getElementById("dafarefaessssd"),
    document.getElementById("dafarefaessssda"),
    "https://www.youtube.com/embed/oo5IqMrx25A?si=XSOSqAxmfM_sU5QI"
  );
  toggleVideo(
    document.getElementById("dfsewewewew"),
    document.getElementById("dfsewewewewa"),
    "https://www.youtube.com/embed/i8KiisMHYQg?si=2FN2Pb54yl5UQpHN"
  );
  toggleVideo(
    document.getElementById("Ecuacionesprimergrado"),
    document.getElementById("Ecuacionesprimergradoa"),
    "https://www.youtube.com/embed/acBAQM8zcv0?si=gYuOkhU1czAGVmGL"
  );
  toggleVideo(
    document.getElementById("métodosdesustituciones"),
    document.getElementById("métodosdesustitucionesa"),
    "https://www.youtube.com/embed/JEbEsF-cUXU?si=Pzey2EGrqMYgk2I7"
  );
  toggleVideo(
    document.getElementById("lsdfiryms"),
    document.getElementById("lsdfirymsa"),
    "https://www.youtube.com/embed/US8mPstfyRo?si=5CpoiPiVhnbScL4W"
  );
  toggleVideo(
    document.getElementById("ttfhfgsdgtsgdfgs"),
    document.getElementById("ttfhfgsdgtsgdfgsa"),
    "https://www.youtube.com/embed/eg6G58Z8EOU?si=GxyGpUfl2ngXVmiM"
  );
  toggleVideo(
    document.getElementById("tgtgtgtgt"),
    document.getElementById("tgtgtgtgta"),
    "https://www.youtube.com/embed/tYyHeAPB-MQ?si=EGVSV03UWUn4FsPn"
  );
  toggleVideo(
    document.getElementById("gtgtefadgd"),
    document.getElementById("gtgtefadgda"),
    "https://www.youtube.com/embed/FBbmHM7YcFM?si=hFQf1LaMUMETKbV9"
  );
  toggleVideo(
    document.getElementById("sfasfsadfasdfsd"),
    document.getElementById("sfasfsadfasdfsda"),
    "https://www.youtube.com/embed/RLmNJ9FeIHI?si=k4b_rl2vFYLA8T0u"
  );
  toggleVideo(
    document.getElementById("sfasfsadfasdfsd"),
    document.getElementById("sfasfsadfasdfsda"),
    "https://www.youtube.com/embed/RLmNJ9FeIHI?si=k4b_rl2vFYLA8T0u"
  );
  toggleVideo(
    document.getElementById("sfasfsadfasdfsd"),
    document.getElementById("sfasfsadfasdfsda"),
    "https://www.youtube.com/embed/RLmNJ9FeIHI?si=k4b_rl2vFYLA8T0u"
  );
  toggleVideo(
    document.getElementById("sfasfsadfasdfsd"),
    document.getElementById("sfasfsadfasdfsda"),
    "https://www.youtube.com/embed/RLmNJ9FeIHI?si=k4b_rl2vFYLA8T0u"
  );





